name: ci
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    # Make the env available to every step in this job
    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
      HUGGINGFACE_HUB_TOKEN: ${{ secrets.HF_TOKEN }}  # alias some tools look for
      GIT_LFS_SKIP_SMUDGE: "1"

    steps:
      - uses: actions/checkout@v4
        # with:
        #   lfs: false   # default; keep false to avoid huge LFS downloads

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Install deps
        run: pip install -r requirements.txt

      # (Optional) one-line sanity check; remove once stable
      - name: Sanity check env
        shell: bash
        run: |
          echo "HF present? $(python - <<'PY'
          import os; print(bool(os.getenv('HF_TOKEN') or os.getenv('HUGGINGFACE_HUB_TOKEN')))
          PY)"

      - name: Hugging Face login (skip on forked PRs)
        if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository }}
        run: huggingface-cli login --token "$HF_TOKEN" --add-to-git-credential

      - name: Make run executable
        run: chmod +x ./run

      - name: Run tests
        run: ./run test

      - name: Run app
        run: ./run "${{ github.event.inputs.url_file || 'example_urls.txt' }}" | tee results.ndjson

      - uses: actions/upload-artifact@v4
        with:
          name: results-ndjson
          path: results.ndjson
