name: test-secrets

on: workflow_dispatch: {}   # lets you trigger it manually in the Actions tab

jobs:
  check-secret:
    runs-on: ubuntu-latest
    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Print env length
        run: echo "HF_TOKEN length = ${#HF_TOKEN:-0}"

      - name: Check in Python
        run: |
          python - <<'PY'
          import os
          tok = os.getenv("HF_TOKEN")
          print("Token present?", bool(tok))
          if tok:
              print("First 5 chars:", tok[:5] + "...")
          else:
              print("No token found")
          PY
