name: test-secrets
on: push

jobs:
  check-secret:
    runs-on: ubuntu-latest
    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Print env presence (bash)
        shell: bash
        run: |
          if [ -z "$HF_TOKEN" ]; then
            echo "HF_TOKEN is empty"
          else
            echo "HF_TOKEN is set, length=${#HF_TOKEN}"
          fi

      - name: Check in Python
        run: |
          python - <<'PY'
          import os
          tok = os.getenv("HF_TOKEN")
          print("Token present?", bool(tok))
          if tok:
              print("First 5 chars:", tok[:5] + "...")
          PY
